name: Multiverse-Inventories
main: com.onarandombox.multiverseinventories.MultiverseInventories
version: maven-version-number
api-version: 1.13
author: dumptruckman
depend: ['Multiverse-Core']
softdepend: [MultiInv, WorldInventories, Multiverse-Adventure]

commands:
  mvinv:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvaddshares:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvaddshare, mvinvadds, mvinvas ]
    usage: /<command>
  mvinvaddworld:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvaddw, mvinvaw ]
    usage: /<command>
  mvinvcreategroup:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvcreateg, mvinvcg ]
    usage: /<command>
  mvinvdeletegroup:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvdeleteg, mvinvdg ]
    usage: /<command>
  mvinvgroup:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvg ]
    usage: /<command>
  mvinvimport:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvim ]
    usage: /<command>
  mvinvinfo:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvi ]
    usage: /<command>
  mvinvlist:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvl ]
    usage: /<command>
  mvinvmigrate:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvreload:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvremoveshares:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvrmshares, mvinvremoveshare, mvinvrmshare, mvinvremoves,mvinvrs mvinvrms, mvinvrs ]
    usage: /<command>
  mvinvremoveworld:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvremovew, mvinvrmworld, mvinvrmw, mvinvrw ]
    usage: /<command>
  mvinvspawn:
    description: Generic Multiverse-Inventories Command
    aliases: [ mvinvs, gspawn, ispawn ]
    usage: /<command>
  mvinvtoggle:
    description: Generic Multiverse-Inventories Command
    usage: /<command>

awareness:
- !@UTF8