name: Multiverse-Inventories
main: com.onarandombox.multiverseinventories.MultiverseInventories
version: ${version}
api-version: 1.13
authors: ['dumptruckman', 'benwoo1110']
depend: ['Multiverse-Core']
softdepend: [MultiInv, WorldInventories]
