name: Multiverse-Inventories
main: com.onarandombox.multiverseinventories.MultiverseInventories
version: maven-version-number
author: dumptruckman
depend: ['Multiverse-Core']
softdepend: [MultiInv, WorldInventories, Multiverse-Adventure]

commands:
  mvinv:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvinfo:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvi:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvim:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvimport:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvlist:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvl:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvreload:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvaddshares:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvadds:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvas:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvraddshare:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvaddword:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvaddw:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvaw:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvremoveshares:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvremoveshare:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvremoves:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrmshares:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrmshare:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrms:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrs:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvremoveworld:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvremovew:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrmworld:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrmw:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvrw:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvspawn:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvs:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  ispawn:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  gspawn:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvdebug:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
  mvinvd:
    description: Generic Multiverse-Inventories Command
    usage: /<command>

awareness:
- !@UTF8